services:
  # Supabase Local Development Stack
  supabase-db:
    image: supabase/postgres:15.1.0.117
    container_name: supabase-db
    ports:
      - '54322:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - supabase_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  supabase-auth:
    image: supabase/gotrue:v2.132.3
    container_name: supabase-auth
    ports:
      - '9999:9999'
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: http://localhost:3000,http://localhost:54321
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: false
      GOTRUE_MAILER_AUTOCONFIRM: true
      GOTRUE_SMS_AUTOCONFIRM: true
      API_EXTERNAL_URL: http://localhost:54321
    depends_on:
      - supabase-db
    restart: unless-stopped

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    container_name: supabase-rest
    ports:
      - '3000:3000'
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      PGRST_DEFAULT_RLS: 1
      PGRST_DB_USE_LEGACY_GUCS: 0
    depends_on:
      - supabase-db
    restart: unless-stopped

  # supabase-realtime:
  #   image: supabase/realtime:v2.25.35
  #   container_name: supabase-realtime
  #   ports:
  #     - '4000:4000'
  #   environment:
  #     DB_HOST: supabase-db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #     PORT: 4000
  #     JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  #     REPLICATION_MODE: RLS
  #     REPLICATION_POLL_INTERVAL: 100
  #     SECURE_CHANNELS: true
  #     SECRET_KEY_BASE: super-secret-key-base-with-at-least-64-characters-long-for-realtime-service
  #     APP_NAME: supabase_realtime
  #     DB_SSL: false
  #     DB_SSL_MODE: disable
  #   depends_on:
  #     - supabase-db
  #   restart: unless-stopped

  supabase-storage:
    image: supabase/storage-api:v0.40.4
    container_name: supabase-storage
    ports:
      - '5000:5000'
    environment:
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PROJECT_REF: local
      POSTGREST_URL: http://supabase-rest:3000
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      PGOPTIONS: -c search_path=storage,public
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
    volumes:
      - supabase_storage_data:/var/lib/storage
    depends_on:
      - supabase-rest
      - supabase-db
    restart: unless-stopped

  supabase-dashboard:
    image: supabase/studio:latest
    container_name: supabase-dashboard
    ports:
      - '54323:3000'
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: postgres
      DEFAULT_ORGANIZATION_NAME: Default Organization
      DEFAULT_PROJECT_NAME: Default Project
      SUPABASE_URL: http://localhost:54321
      SUPABASE_PUBLIC_URL: http://localhost:54321
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - supabase-meta
    restart: unless-stopped

  supabase-meta:
    image: supabase/postgres-meta:v0.68.0
    container_name: supabase-meta
    ports:
      - '8080:8080'
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: postgres
      PG_META_READONLY_MODE: false
    depends_on:
      - supabase-db
    restart: unless-stopped

  supabase-kong:
    image: kong:2.8.1
    container_name: supabase-kong
    ports:
      - '54321:8000'
      - '54324:8443'
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth,datadog,file-log,http-log,udp-log,tcp-log,loggly,statsd,ip-restriction,request-size-limiting,rate-limiting,response-ratelimiting,aws-lambda,azure-functions,proxy-cache,correlation-id,pre-function,post-function
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml:ro
    depends_on:
      - supabase-auth
      - supabase-rest
      - supabase-storage
      - supabase-meta
    restart: unless-stopped

volumes:
  supabase_db_data:
  supabase_storage_data:
